sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
compiler:
  - clang
#addons:
#    apt:
#      sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7', 'kalakris-cmake']
#      packages: ['clang-3.7', 'cmake', '', '', '']
#env: COMPILER=clang++-3.7
before_install:
  - sudo add-apt-repository -y ppa:h-rayflood/llvm
  - sudo apt-get update -qq
install:
  - sudo apt-get install --allow-unauthenticated -qq clang-3.4 util-linux libblkid1 libblkid-dev
  - export CXX="clang++-3.4"