sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
addons:
    apt:
      sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7', 'kalakris-cmake']
      packages: ['clang-3.7', 'cmake']
env: COMPILER=clang++-3.7